# Generated by Django 4.0.6 on 2022-07-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_theaters', '0001_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie_theater_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_theaters.movietheater'),
            preserve_default=False,
        ),
    ]
