# Generated by Django 4.0.6 on 2022-07-19 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='ticket_seat_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
