# Generated by Django 4.0.6 on 2022-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatMap', models.ManyToManyField(related_name='seatMap', to='seats.seat')),
            ],
        ),
    ]
