# Generated by Django 4.0.6 on 2022-07-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_active',
            new_name='status_active',
        ),
    ]
