# Generated by Django 4.0.6 on 2022-07-19 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_ticket_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
