# Generated by Django 4.0.6 on 2022-07-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
