# Generated by Django 4.0.6 on 2022-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('movie_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='schedule',
            field=models.ManyToManyField(related_name='sessions', to='schedules.schedule'),
        ),
    ]
