# Generated by Django 4.0.6 on 2022-07-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_sessions', '0001_initial'),
        ('movies', '0001_initial'),
        ('schedules', '0001_initial'),
        ('movie_theaters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_sessions', to='movies.moviesmodel'),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_sessions', to='movie_theaters.movietheater'),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='schedule',
            field=models.ManyToManyField(null=True, related_name='sessions', to='schedules.schedule'),
        ),
    ]
