# Generated by Django 4.0.6 on 2022-07-16 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='cinemas', to=settings.AUTH_USER_MODEL),
        ),
    ]
