# Generated by Django 4.0.6 on 2022-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_alter_cinema_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
    ]
