# Generated by Django 4.0.6 on 2022-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
