# Generated by Django 4.0.6 on 2022-07-19 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_types', '0001_initial'),
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('movie_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='movie_sessions.moviesession')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='payment_types.paymenttype')),
                ('seats', models.ManyToManyField(related_name='tickets', to='seats.seat')),
            ],
        ),
    ]
