# Generated by Django 4.0.6 on 2022-07-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_types', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='payment_types.paymenttype'),
            preserve_default=False,
        ),
    ]
