<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-18 21:12

=======
# Generated by Django 4.0.6 on 2022-07-19 10:44
>>>>>>> f2eb8f707979edcc09abb4d07d6d724f80a6dc38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
